"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var addition = 4 + 4;
var substraction = 10 - 2;
var multiplication = 2 * 4;
var division = 16 / 2;
console.log(addition);
console.log(substraction);
console.log(multiplication);
console.log(division);
