"use strict";
var car = "Fortuner";
var car_color = "Pink";
var car_lenght = 50;
console.log("is car == Fortuner?| predict true");
console.log(car == "Fortuner");
console.log("is car_color == Pink?| predict true");
console.log(car_color == "Pink");
console.log("is car === Fortuner?| predict true");
console.log(car === "Fortuner");
console.log("is car != Landcruiser?| predict true");
console.log(car != "Landcruiser");
console.log("is car_lenght < 100?| predict true");
console.log(car_lenght < 100);
console.log("is car == fortuner?| predict false");
console.log(car == "fortuner");
console.log("is car_color == Black?| predict false");
console.log(car_color == "Black");
console.log("is car !== Fortuner ?| predict false");
console.log(car !== "Fortuner");
console.log("is car == Landcruiser?| predict false");
console.log(car == "Landcruiser");
console.log("is car_lenght > 100?| predict false");
console.log(car_lenght > 100);
